# Generated by Django 3.2.19 on 2023-12-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500)),
                ('size', models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=500)),
                ('products', models.ManyToManyField(to='base.Product')),
            ],
        ),
    ]
