# Generated by Django 3.2.19 on 2023-12-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231207_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='categories',
        ),
    ]
