# Generated by Django 3.2.19 on 2023-12-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_customer_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('New Customer', 'New Customer'), ('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3'), ('Top Rated Customer', 'Top Rated Customer')], default='New Customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='level',
            field=models.CharField(choices=[('New Seller', 'New Seller'), ('Level-1', 'Level-1'), ('Level-2', 'Level-2'), ('Level-3', 'Level-3'), ('Top Rated Seller', 'Top Rated Seller')], default='New Seller', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('address', models.TextField(max_length=500)),
                ('number', models.CharField(max_length=15)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
