# Generated by Django 4.2.8 on 2024-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_itembucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembucket',
            name='product',
        ),
        migrations.AddField(
            model_name='itembucket',
            name='products',
            field=models.ManyToManyField(related_name='products', to='base.product'),
        ),
    ]
