# Generated by Django 4.2.8 on 2024-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_itembucket_product_itembucket_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembucket',
            name='quantity',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itembucket',
            name='products',
            field=models.ManyToManyField(related_name='all_products', to='base.product'),
        ),
    ]
