# Generated by Django 4.2.8 on 2024-02-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_itembucket_quantity_alter_itembucket_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBucket',
        ),
    ]
