# Generated by Django 4.2.8 on 2024-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_itembucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembucket',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
