# Generated by Django 4.2.8 on 2024-02-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_itembucket_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembucket',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
