# Generated by Django 4.2.8 on 2024-02-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_itembucket_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembucket',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
