# Generated by Django 4.2.8 on 2024-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
