# Generated by Django 4.2.8 on 2024-02-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_order_pay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
